### ISSUE TITLE
Menu Bar Red Overlay not working on iOS

### ISSUE THREAD

**Issue by stefanosburbaum** [CreatlV/ths-international-reception#1]
The red overlay of the menu bar is not showing on my iPhone when I click of the menu button. The different menu points do however. 
iPhone 6s, iOS: 12.1.4, webbrowser is Firefox/Safari

**Comment by stefanosburbaum** [comment]
![grafik](https://user-images.githubusercontent.com/58641611/71261071-b7fc5a00-233c-11ea-8d01-5757f3df57c2.png

**Comment by oscsyn** [comment]
I was able to reproduce this myself, no idea why this is the case, but it seems to only happen to old Iphones.

**Comment by oscsyn** [comment]
Saw the same problem i IE11 and was able to fix it there, should be the same case for your Iphone. I don't have my test devices at home so you'll have to verify that it's fixed for me @THS-IR-PM

**Comment by stefanosburbaum** [comment]
can confirm it's fixed
