### ISSUE TITLE
Calendars in Event overview

### ISSUE THREAD

**Issue by stefanosburbaum** [CreatlV/ths-international-reception#18]
Bunch of collection of small and little things:
- can we have multiple calendars in different colours (plus the option to have a text explaining what they stand for?)
- Is it possible that I can see the event details without being forwarded to Google calendar, but rather in our site?

**Comment by CreatlV** [comment]
I believe we could have multiple calendars in multiple colors. I'll try to add that along with the admin page for events. The Event details should work but might be a bit slow on a phone.
