### ISSUE TITLE
Give access to CMS System

### ISSUE THREAD

**Issue by stefanosburbaum** [CreatlV/ths-international-reception#3]
Most important users:
international@thskth.se
pm@thsint.se
info@thsint.se

**Comment by oscsyn** [comment]
I've sent an invention mail to all of them. Then you'll be able to login at https://www.thsint.se/admin/ 
Also, we need to talk about all the pages that is on the website site. I would like to see a justification for every one of them and how they are contributing to our overall goal with the website.
