### ISSUE TITLE
Switch between mobile and desktop is not based on device

### ISSUE THREAD

**Issue by stefanosburbaum** [CreatlV/ths-international-reception#7]
It appears that the view between desktop and mobile version is not switiching based on what the computer says if it's desktop or mobile, but rather on screen size (easy check: make the window on your deskptop pc smaller). then it gets weird becaue it's then switching between the and white menu bar that are also of different thickness

**Comment by CreatlV** [comment]
The standard way is to design based on screen size. There is no full proof way to determine whether a device is mobile or not and the desktop menu would not fit nicely on a smaller screen size than currently set. What could be done is edit the threshold values and work on design to make scaling more seemless. There are several reason why you wouldn't want the video on mobile, for one, mobile users tend to be on pay per use internet and wouldn't want to download more data then necessary.

**Comment by stefanosburbaum** [comment]
fun fact: Google search doesn't work that way

**Comment by stefanosburbaum** [comment]
Wouldn't in then be smarter to have a white menu bar to make that switch less present?

**Comment by CreatlV** [comment]
I retract my statement, there seems to be (mostly) supported ways to identify devices. The design is now  redesigned and the switch may be less prevalent? I'll think about how we could implement responsivness based on device and have the menu working.

**Comment by stefanosburbaum** [comment]
damn I like both designs :D I think if have the same menu bar, once in mobile and once in desktop "design", then the switching between those two will be less extreme. But it's hard to tell since we also switch between the Osqvik video and the courtyard pic. maybe if we extend the video we can just have som screenshots of it and then it doesn't show much at all if you switch

**Comment by stefanosburbaum** [comment]
also: who is who here?

**Comment by oscsyn** [comment]
CreatlV -> Alexander
Jaceww -> Jacob
oscsyn -> Oscar
